A/urls.py
from django.contrib import admin
from django.urls import path , include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("",include("home.urls",namespace="home")),
    path("account/",include("account.urls",namespace="account"))
]

account/urls.py
from . import views
from django.urls import path

app_name = "account"

urlpatterns = [
    path("login/",views.LoginUserView.as_view(),name="login"),
    path("register/",views.RegisterUserView.as_view(),name="register"),
    path("logout/",views.LogoutView.as_view(),name="logout"),
    path("follow/<int:user_id>/",views.FollowUserView.as_view(),name="follow"),
    path("unfollow/<int:user_id>/",views.UnfollowUserView.as_view(),name="unfollow"),
    path("edit_user/",views.EditUserView.as_view(),name="edit_user"),
]

home/urls.py
from . import views
from django.urls import path

app_name = "home"

urlpatterns = [
    path("home/",views.HomeView.as_view(),name="home"),
    path("postdetail/<int:post_id>/<slug:slug_id>/",views.PostDetailView.as_view(),name="postdetail"),
    path("profile/<int:user_id>/",views.ProfileUserView.as_view(),name="profile"),
    path("create/",views.PostCreateView.as_view(),name="create"),
    path("update/<int:post_id>/",views.PostUpdateView.as_view(),name="update"),
    path("delete/<int:post_id>/",views.PostDeleteView.as_view(),name="delete"),
    path("reply/<int:post_id>/<int:comment_id>/",views.CommentReplyView.as_view(),name="add_reply")
    
    
]

home/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
# Create your models here.




class Post(models.Model):
    user = models.ForeignKey(User,on_delete=models.CASCADE, related_name="posts")
    body = models.TextField(max_length=200)
    slug = models.SlugField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ("-created",)



    def __str__(self):
        return f"{self.slug} - {self.created}"
    
    def get_absolute_url(self):
        return reverse("home:postdetail",args=[self.id,self.slug])
    



class Comment(models.Model):
    user = models.ForeignKey(User,on_delete=models.CASCADE, related_name="ucomments")
    post = models.ForeignKey(Post,on_delete=models.CASCADE, related_name="pcomments")
    is_reply = models.BooleanField(default=False)
    reply = models.ForeignKey("self",on_delete=models.CASCADE, related_name="rcomments",blank=True,null=True)
    body = models.TextField(max_length=200)
    created = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f"{self.user} - {self.post.slug}"

home/forms.py
from django import forms
from .models import Post , Comment

class PostCreateForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ("body","slug")
    


class CommentCreateForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ("body",)
        widgets = {
            "body":forms.Textarea(attrs={"placeholder":"put your comment here","class":"form-control"})
        }


class CommentReplyForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ("body",)
        widgets = {
            "body":forms.Textarea(attrs={"placeholder":"put your comment here","class":"form-control"})
        }


class SearchForm(forms.Form):
    search = forms.CharField(widget=(forms.TextInput(attrs={"placeholder":"Search here","class":"form-control"})))

home/views.py
from django.shortcuts import render , redirect
from django.shortcuts import get_object_or_404 
from django.views import View
from .models import Post , Comment
from django.contrib.auth.models import User
from django.contrib.auth.mixins import LoginRequiredMixin
from .forms import PostCreateForm , CommentCreateForm ,CommentReplyForm , SearchForm
from django.contrib import messages
from account.models import Relation
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from django.contrib.auth.mixins import UserPassesTestMixin
from utils import IsAdminUserMixin
# Create your views here.


class HomeView(View):
    form_class = SearchForm
    def get(self,request):
        posts = Post.objects.all()
        if request.GET.get("search"):
            posts = posts.filter(body__contains=request.GET["search"])
        return render(request,"home/home.html",{"posts":posts,"form":self.form_class})
    
class PostDetailView(View):
    form_class = CommentCreateForm
    form_class_reply = CommentReplyForm
    def setup(self, request, *args, **kwargs):
        self.post_instance = get_object_or_404(Post,pk=kwargs["post_id"],slug=kwargs["slug_id"])
        return super().setup(request, *args, **kwargs)

    def get(self,request,post_id,slug_id):
        form  = self.form_class()
        comments = self.post_instance.pcomments.filter(is_reply=False)
        return render(request,"home/postdetail.html",{"post":self.post_instance,"comments":comments,"form":form,"reply_form":self.form_class_reply})
    
    @method_decorator(login_required)
    def post(self,request,post_id,slug_id):
        form = self.form_class(request.POST)
        if form.is_valid():
            new_form = form.save(commit=False)
            new_form.user = request.user
            new_form.post = self.post_instance
            new_form.save()
            messages.success(request,"Comment has been sent successfully","success")
            return redirect("home:postdetail",self.post_instance.id,self.post_instance.slug)
        
class ProfileUserView(LoginRequiredMixin,View):
    def get(self,request,user_id):
        is_followed = False
        user = get_object_or_404(User,pk=user_id)
        relation = Relation.objects.filter(from_user=request.user, to_user=user)
        followers = Relation.follower_count(self,user_id)
        if relation.exists():
            is_followed = True
        posts = Post.objects.filter(user=user)
        return render(request,"home/profile.html",{"posts":posts,"user":user,"is_followed":is_followed,"followers":followers})




class PostCreateView(LoginRequiredMixin,View):
    form_class = PostCreateForm

    def get(self,request):
        form = self.form_class()
        return render(request,"home/create.html",{"form":form})
    
    def post(self,request):
        form = self.form_class(request.POST)
        if form.is_valid():
            new_form = form.save(commit=False)
            new_form.user = request.user
            new_form.save()
            messages.success(request,"Post has been created successfully","success")
            return redirect("home:profile",request.user.id)
        return render(request,"home/create.html",{"form":form})


class PostUpdateView(LoginRequiredMixin,View):
    form_class = PostCreateForm

    def setup(self, request, *args, **kwargs):
        self.post_instance = get_object_or_404(Post,pk=kwargs["post_id"])
        return super().setup(request, *args, **kwargs)


    def dispatch(self, request, *args, **kwargs):
        if  request.user.id != self.post_instance.user.id:
            messages.error(request,"You cant update this post","danger")
            return redirect("home:home")
        return super().dispatch(request, *args, **kwargs)


    def get(self,request,post_id):
        form = self.form_class(instance=self.post_instance)
        return render(request,"home/update.html",{"form":form})
    def post(self,request,post_id):
        form = self.form_class(request.POST,instance=self.post_instance)
        if form.is_valid():
            form.save()
            messages.success(request,"Post has been successfully updated","success")
            return redirect("home:postdetail",self.post_instance.id,self.post_instance.slug)
        form = self.form_class(request.POST,instance=self.post_instance)


class PostDeleteView(LoginRequiredMixin,View):
    def get(self,request,post_id):
        post = get_object_or_404(Post,id=post_id)
        if request.user.id != post.user.id:
            messages.error(request,"You cant delete this post","danger")
            return redirect("home:home")
        else:
            post.delete()
            messages.success(request,"Post has been deleted successsfully","success")
            return redirect("home:profile",request.user.id)
        


class CommentReplyView(IsAdminUserMixin,View):
    form_class_reply =  CommentReplyForm

    def post(self,request,post_id,comment_id):
        post = get_object_or_404(Post,id=post_id)
        comment = Comment.objects.get(id=comment_id)
        form = self.form_class_reply(request.POST)
        if form.is_valid():
            new_form = form.save(commit=False)
            new_form.user = request.user
            new_form.post = post
            new_form.reply = comment
            new_form.is_reply = True
            new_form.save()
            messages.success(request,"reply has beem  submitted successfully","success")
        return redirect("home:postdetail",post.id,post.slug)
    

home/templates/home/create.html
{% extends 'base.html' %}

{% block content %}
    <h1>Create Post</h1>
    <form action="" method="post">
        {% csrf_token %}
        {{form.as_p}}
        <input type="submit" value="Create">
    </form>
{% endblock %} 

home/templates/home/home.html
{% extends 'base.html' %}

{% block content %}

    <h1>Hello world</h1>
    <form action="" method="get" class="col-md-6">
        {{ form.as_p }}
        <input type="submit" value="Search">
    </form><br><hr>

    {% for post in posts %}
        {{ forloop.counter }} . 
        <a href="{{ post.get_absolute_url }}">{{post.body|truncatewords:4}}</a><br>
    {% endfor  %}

{% endblock %}

home/templates/home/postdetail.html
{% extends 'base.html' %}  



{% block content %}
    {% if request.user.id == post.user.id %}
    <a href="{% url 'home:delete' post.id %}" class="btn btn-danger">Delete</a>
    <a href="{% url 'home:update' post.id %}" class="btn btn-info">Update</a><br>
    {% endif %}


    <a href="{% url 'home:profile' post.user.id %}">{{ post.user.username }}</a>
    <p>{{post.created|date:'Y M d'}}</p>
    <h5>{{post.body}}</h5><hr>


    {% if request.user.is_authenticated %}
        <form action="" method="post" class="col-md-6">
            {% csrf_token %}
            {{form.as_p}}
            <input type="submit" value="Send">
        </form><br>
    {% else %}
        <p class="alert alert-danger">Only logged in users can comment . </p>
    {% endif %}
   



    {% for comment in comments %}
        <div class="card bg-dark text-white">
            <p class="card-header">{{comment.user}}  |  {{comment.created|timesince}} ago</p>
            <p class="card-body">{{comment.body}}</p>
            {% if request.user.is_authenticated %}  
                <form action="{% url 'home:add_reply' post.id comment.id %}" method="post" class="col-md-6">
                    {% csrf_token %}
                    {{reply_form.as_p}}
                    <input type="submit"value="Send">
                </form><br>
            {% endif %}



                {% with replies=comment.rcomments.all %}
                {% for reply in replies %}
                    <div class="card bg-primary text-white">
                        <p class="card-header">{{ reply.user }} | {{ reply.created|timesince }}</p>
                        <p class="card-body">{{ reply.body }}</p>
                    </div><br>
                {% endfor %}
            {% endwith %}
        </div><br>
        




    {% empty %}
        <p class="alert alert-warning">No comments here </p>
    {% endfor %}





{% endblock  %}

home/templates/home/profile.html
{% extends 'base.html' %}

{% block content %}

    <h3>{{user.username}}</h3><br>
    <p>{{followers}} follower</p>

    {% if request.user.id == user.id %}
        <a href="{% url 'home:create' %}" class="btn btn-info">Create Post</a>
        <a href="{% url 'account:edit_user' %}" class="btn btn-primary">Edit Profile</a>
    {% else %}
        {% if  not is_followed %}
            <a href="{% url 'account:follow' user.id %}" class="btn btn-info">Follow</a>
        {% else %}
            <a href="{% url 'account:unfollow' user.id %}" class="btn btn-info">UnFollow</a>
        {% endif %}
    {% endif %}


    <div class="card">
        {% for post in posts %}
            <a href="{{ post.get_absolute_url }}" class="card-body">{{post.body|truncatewords:4}}</a>
        {% endfor %}
    </div>
{% endblock %}

home/templates/home/update.html
{% extends 'base.html' %}

{% block content %}
    <h1>Update Post</h1>
    <form action="" method="post">
        {% csrf_token %}
        {{form.as_p}}
        <input type="submit" value="Update">
    </form>
{% endblock %} 