A/urls.py
from django.contrib import admin
from django.urls import path , include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("",include("home.urls",namespace="home")),
    path("account/",include("account.urls",namespace="account"))
]

account/urls.py
from . import views
from django.urls import path

app_name = "account"

urlpatterns = [
    path("login/",views.LoginUserView.as_view(),name="login"),
    path("register/",views.RegisterUserView.as_view(),name="register"),
    path("logout/",views.LogoutView.as_view(),name="logout"),
    path("follow/<int:user_id>/",views.FollowUserView.as_view(),name="follow"),
    path("unfollow/<int:user_id>/",views.UnfollowUserView.as_view(),name="unfollow"),
    path("edit_user/",views.EditUserView.as_view(),name="edit_user"),
]

home/urls.py
from . import views
from django.urls import path

app_name = "home"

urlpatterns = [
    path("home/",views.HomeView.as_view(),name="home"),
    path("postdetail/<int:post_id>/<slug:slug_id>/",views.PostDetailView.as_view(),name="postdetail"),
    path("profile/<int:user_id>/",views.ProfileUserView.as_view(),name="profile"),
    path("create/",views.PostCreateView.as_view(),name="create"),
    path("update/<int:post_id>/",views.PostUpdateView.as_view(),name="update"),
    path("delete/<int:post_id>/",views.PostDeleteView.as_view(),name="delete"),
    path("reply/<int:post_id>/<int:comment_id>/",views.CommentReplyView.as_view(),name="add_reply")
    
    
]

templates/inc/messages.html
{% if messages %}
    {% for msg in messages %}
        <p class="alert alert-{{msg.tags}}">{{msg}}</p>
    {% endfor %}
{% endif %}

templates/inc/navbar.html
<nav class="navbar navbar-expand-lg bg-body-tertiary" data-bs-theme="dark">
    <div>
        <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'home:home' %}">Home</a>
        {% if  not request.user.is_authenticated %}
            <a class="navbar-brand" href="{% url 'account:login' %}">Login</a>
            <a class="navbar-brand" href="{% url 'account:register' %}">Register</a>
        {% else %}
            <a class="navbar-brand" href="{% url 'account:logout' %}">Logout</a>
            <a class="navbar-brand" href="{% url 'home:profile' request.user.id %}">Profile</a>
        {% endif %}
        </div>
    </div>
  </nav>